/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-04-25 16:52:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.themes.default_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fform_0026_005fmethod_005fcommandName_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005finput_0026_005frequired_005fplaceholder_005fpath_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fpassword_0026_005frequired_005fplaceholder_005fpath_005fid_005fclass_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fform_0026_005fmethod_005fcommandName_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005finput_0026_005frequired_005fplaceholder_005fpath_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fpassword_0026_005frequired_005fplaceholder_005fpath_005fid_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fform_0026_005fmethod_005fcommandName_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fspring_005finput_0026_005frequired_005fplaceholder_005fpath_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fpassword_0026_005frequired_005fplaceholder_005fpath_005fid_005fclass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<meta name=description content=\"Home\">\r\n");
      if (_jspx_meth_tiles_005finsertAttribute_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\trel=\"stylesheet\" media=\"screen\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t");

			if (request.getParameter("action") != null) {
				String action = request.getParameter("action");
				if (action.equals("repass")) {
				
      out.write("\r\n");
      out.write("\t\t<div id=\"changepassword\" style=\"margin-top: 50px;\"\r\n");
      out.write("\t\t\tclass=\"mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-info\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-title\">Change your password</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div style=\"padding-top: 30px\" class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" class=\"form-horizontal\" action=\"changepassword\" id=\"changepassword\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"password\" class=\"col-md-3 control-label\">Password\r\n");
      out.write("\t\t\t\t\t\t\t\t*</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"passwd form-control\" name=\"passwd\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Password\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"re-passwd\" class=\"col-md-3 control-label\">Re-Password\r\n");
      out.write("\t\t\t\t\t\t\t\t*</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"re-passwd form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"re-passwd\" placeholder=\"Re-Enter Password\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: none\" id=\"signup-err\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"alert alert-danger col-sm-12 signup-err\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-top: 10px\" class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Button -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-12 controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" id=\"btn-login\" class=\"btn btn-primary btn-default btn-block\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"Change\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t");

				} 
			}else {
		
      out.write("\r\n");
      out.write("\t\t<div id=\"loginbox\" style=\"margin-top: 50px;\"\r\n");
      out.write("\t\t\tclass=\"mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-info\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-title\">Sign In</div>\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tstyle=\"float: right; font-size: 80%; position: relative; top: -10px\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tonClick=\"$('#loginbox').hide(); $('#forgotpassbox').show()\">Forgot\r\n");
      out.write("\t\t\t\t\t\t\tpassword?</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div style=\"padding-top: 30px\" class=\"panel-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"display: none ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${display}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" id=\"login-alert\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"alert alert-danger col-sm-12\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_spring_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"signupbox\" style=\"display: none; margin-top: 50px\"\r\n");
      out.write("\t\t\tclass=\"mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-info\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-title\">Sign Up</div>\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tstyle=\"float: right; font-size: 85%; position: relative; top: -10px\">\r\n");
      out.write("\t\t\t\t\t\t<a id=\"signinlink\" href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"$('#signupbox').hide();$('#forgotpassbox').hide(); $('#loginbox').show()\">Sign\r\n");
      out.write("\t\t\t\t\t\t\tIn</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<form action=\"register\" id=\"signupform\" class=\"form-horizontal\"\r\n");
      out.write("\t\t\t\t\t\trole=\"form\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"signupalert\" style=\"display: none\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"alert alert-danger\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>Error:</p>\r\n");
      out.write("\t\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"email\" class=\"col-md-3 control-label\">Email *</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"email form-control\" name=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Email Address\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"firstname\" class=\"col-md-3 control-label\">First\r\n");
      out.write("\t\t\t\t\t\t\t\tName *</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"firstname form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"firstname\" placeholder=\"First Name\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"lastname\" class=\"col-md-3 control-label\">Last\r\n");
      out.write("\t\t\t\t\t\t\t\tName *</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"lastname form-control\" name=\"lastname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Last Name\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"password\" class=\"col-md-3 control-label\">Password\r\n");
      out.write("\t\t\t\t\t\t\t\t*</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"passwd form-control\" name=\"passwd\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Password\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"re-passwd\" class=\"col-md-3 control-label\">Re-Password\r\n");
      out.write("\t\t\t\t\t\t\t\t*</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"re-passwd form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"re-passwd\" placeholder=\"Password\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: none\" id=\"signup-err\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"alert alert-danger col-sm-12 signup-err\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Button -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-offset-3 col-md-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"btn-signup\" type=\"submit\" class=\"btn btn-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-hand-right\"></i>Sign Up\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"margin-left: 8px;\">or</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div style=\"border-top: 1px solid #999; padding-top: 20px\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-offset-3 col-md-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"btn-fbsignup\" type=\"button\" class=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>   Sign Up with Facebook\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Start Forgot pass -->\r\n");
      out.write("\t\t<div id=\"forgotpassbox\" style=\"display: none; margin-top: 50px\"\r\n");
      out.write("\t\t\tclass=\"mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-info\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-title\">Recovery password</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div style=\"padding-top: 30px\" class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" class=\"form-horizontal\" action=\"fogotpassword\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-bottom: 25px\" class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i></span> <input type=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"Input your email\" required=\"required\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-top: 10px\" class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Button -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-12 controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" id=\"btn-login\" class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"Get password!\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border-top: 1px solid #888; padding-top: 15px; font-size: 85%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tDon't have an account! <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonClick=\"$('#loginbox').hide();$('#forgotpassbox').hide(); $('#signupbox').show()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tSign Up Here </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(\r\n");
      out.write("\t\t\tfunction () {\r\n");
      out.write("\t\t\t    $(\".passwd\").change(\r\n");
      out.write("\t\t\t    function () {\r\n");
      out.write("\t\t\t        // Alert for password < 6 words\r\n");
      out.write("\t\t\t        if ($(\".passwd\").val().length <= 6) {\r\n");
      out.write("\t\t\t            $(\"#signup-err\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t            $(\"#signup-err\").html(\"Password needs to have at least six characters!\");\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        if ($(\".passwd\").val().length > 6) {\r\n");
      out.write("\t\t\t            $(\"#signup-err\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    })\r\n");
      out.write("\t\t\t    $(\"#changepassword\").submit(function(){\r\n");
      out.write("\t\t\t    \tif ($(\".passwd\").val().length > 6) {\r\n");
      out.write("\t\t                if ($(\".passwd\").val() == $(\".re-passwd\").val()) {\r\n");
      out.write("\t\t                    return true;\r\n");
      out.write("\t\t                } else {\r\n");
      out.write("\t\t                    $(\"#signup-err\").css(\"display\", \"block\");\r\n");
      out.write("\t\t                    $(\"#signup-err\").html(\"Password and Re-Password not same!\");\r\n");
      out.write("\t\t                    return false;\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t            } else {\r\n");
      out.write("\t\t                $(\"#signup-err\").css(\"display\", \"block\");\r\n");
      out.write("\t\t                $(\"#signup-err\").html(\"Password needs to have at least six characters!\");\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t\t    })\r\n");
      out.write("\t\t\t    $(\"#signupform\").submit(\r\n");
      out.write("\r\n");
      out.write("\t\t\t    function () {\r\n");
      out.write("\t\t\t        if ($(\".email\").val() != '' && $(\".firstname\").val() != '' && $(\".lastname\").val() != '' && $(\".passwd\") != '') {\r\n");
      out.write("\t\t\t            if ($(\".passwd\").val().length > 6) {\r\n");
      out.write("\t\t\t                if ($(\".passwd\").val() == $(\".re-passwd\").val()) {\r\n");
      out.write("\t\t\t                    return true;\r\n");
      out.write("\t\t\t                } else {\r\n");
      out.write("\t\t\t                    $(\"#signup-err\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t                    $(\"#signup-err\").html(\"Password and Re-Password not same!\");\r\n");
      out.write("\t\t\t                    return false;\r\n");
      out.write("\t\t\t                }\r\n");
      out.write("\t\t\t            } else {\r\n");
      out.write("\t\t\t                $(\"#signup-err\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t                $(\"#signup-err\").html(\"Password needs to have at least six characters!\");\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t        } else {\r\n");
      out.write("\t\t\t            return false;\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f0 = (new org.apache.tiles.jsp.taglib.InsertAttributeTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertAttribute_005f0);
    _jspx_th_tiles_005finsertAttribute_005f0.setJspContext(_jspx_page_context);
    // /WEB-INF/views/themes/default/login.jsp(11,0) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f0.setName("head");
    // /WEB-INF/views/themes/default/login.jsp(11,0) name = ignore type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f0.setIgnore(true);
    _jspx_th_tiles_005finsertAttribute_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertAttribute_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/themes/default/login.jsp(13,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/resources/themes/default/css/style-signin.css");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_spring_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_spring_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fspring_005fform_0026_005fmethod_005fcommandName_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    _jspx_th_spring_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fform_005f0.setParent(null);
    // /WEB-INF/views/themes/default/login.jsp(86,5) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fform_005f0.setCommandName("User");
    // /WEB-INF/views/themes/default/login.jsp(86,5) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fform_005f0.setMethod("post");
    // /WEB-INF/views/themes/default/login.jsp(86,5) null
    _jspx_th_spring_005fform_005f0.setDynamicAttribute(null, "class", "form-horizontal");
    // /WEB-INF/views/themes/default/login.jsp(86,5) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fform_005f0.setAction("login");
    int[] _jspx_push_body_count_spring_005fform_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fform_005f0 = _jspx_th_spring_005fform_005f0.doStartTag();
      if (_jspx_eval_spring_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<div style=\"margin-bottom: 25px\" class=\"input-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i\r\n");
          out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i></span>\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_spring_005finput_005f0(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<div style=\"margin-bottom: 25px\" class=\"input-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i\r\n");
          out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i></span>\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_spring_005fpassword_005f0(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"checkbox\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<label> <input id=\"login-remember\" type=\"checkbox\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tvalue=\"1\" /> Remember me ?\r\n");
          out.write("\t\t\t\t\t\t\t\t</label>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<div style=\"margin-top: 10px\" class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<!-- Button -->\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"col-sm-12 controls\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" id=\"btn-login\" class=\"btn btn-success\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tvalue=\"Login\" />\r\n");
          out.write("\t\t\t\t\t\t\t\t<!-- \r\n");
          out.write("\t\t\t\t\t\t\t\t<a id=\"btn-fblogin\" href=\"#\" class=\"btn btn-primary\">Login\r\n");
          out.write("\t\t\t\t\t\t\t\t\twith Facebook</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t -->\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 control\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<div\r\n");
          out.write("\t\t\t\t\t\t\t\t\tstyle=\"border-top: 1px solid #888; padding-top: 15px; font-size: 85%\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\tDon't have an account! <a href=\"#\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tonClick=\"$('#loginbox').hide(); $('#signupbox').show()\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tSign Up Here </a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_spring_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_spring_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fform_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fform_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fform_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005fform_0026_005fmethod_005fcommandName_005fclass_005faction.reuse(_jspx_th_spring_005fform_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spring_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspring_005finput_0026_005frequired_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_spring_005finput_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
    // /WEB-INF/views/themes/default/login.jsp(91,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005finput_005f0.setPath("email");
    // /WEB-INF/views/themes/default/login.jsp(91,7) null
    _jspx_th_spring_005finput_005f0.setDynamicAttribute(null, "class", "form-control");
    // /WEB-INF/views/themes/default/login.jsp(91,7) null
    _jspx_th_spring_005finput_005f0.setDynamicAttribute(null, "placeholder", "Input your email");
    // /WEB-INF/views/themes/default/login.jsp(91,7) null
    _jspx_th_spring_005finput_005f0.setDynamicAttribute(null, "required", "required");
    int[] _jspx_push_body_count_spring_005finput_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005finput_005f0 = _jspx_th_spring_005finput_005f0.doStartTag();
      if (_jspx_th_spring_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005finput_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005finput_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005finput_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005finput_0026_005frequired_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_spring_005finput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fpassword_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:password
    org.springframework.web.servlet.tags.form.PasswordInputTag _jspx_th_spring_005fpassword_005f0 = (org.springframework.web.servlet.tags.form.PasswordInputTag) _005fjspx_005ftagPool_005fspring_005fpassword_0026_005frequired_005fplaceholder_005fpath_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.PasswordInputTag.class);
    _jspx_th_spring_005fpassword_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fpassword_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
    // /WEB-INF/views/themes/default/login.jsp(97,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fpassword_005f0.setPath("passWord");
    // /WEB-INF/views/themes/default/login.jsp(97,7) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fpassword_005f0.setId("login-username");
    // /WEB-INF/views/themes/default/login.jsp(97,7) null
    _jspx_th_spring_005fpassword_005f0.setDynamicAttribute(null, "class", "form-control");
    // /WEB-INF/views/themes/default/login.jsp(97,7) null
    _jspx_th_spring_005fpassword_005f0.setDynamicAttribute(null, "placeholder", "Your password");
    // /WEB-INF/views/themes/default/login.jsp(97,7) null
    _jspx_th_spring_005fpassword_005f0.setDynamicAttribute(null, "required", "required");
    int[] _jspx_push_body_count_spring_005fpassword_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fpassword_005f0 = _jspx_th_spring_005fpassword_005f0.doStartTag();
      if (_jspx_th_spring_005fpassword_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fpassword_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fpassword_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fpassword_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005fpassword_0026_005frequired_005fplaceholder_005fpath_005fid_005fclass_005fnobody.reuse(_jspx_th_spring_005fpassword_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f1 = (new org.apache.tiles.jsp.taglib.InsertAttributeTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertAttribute_005f1);
    _jspx_th_tiles_005finsertAttribute_005f1.setJspContext(_jspx_page_context);
    // /WEB-INF/views/themes/default/login.jsp(256,1) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f1.setName("footer");
    // /WEB-INF/views/themes/default/login.jsp(256,1) name = ignore type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f1.setIgnore(true);
    _jspx_th_tiles_005finsertAttribute_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertAttribute_005f1);
    return false;
  }
}
