/*
 * Class name:
 * 
 * Version information:
 *
 * Date: 10-July-2014
 * 
 * Copyright notice: none
 * 
 * Modification Logs:
 *     DATE         AUTHOR             DESCRIPTION
 *  --------------------------------------------------------
 *  10-July-2014    XXXXXX          Create java class file
 */
package com.htqlbh.model;

import java.util.Date;

/**
 * Payment generated by hbm2java.
 */
public class Payment implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** The payment id. */
    private int paymentId;
    
    /** The sales person. */
    private SalesPerson salesPerson;
    
    /** The customer. */
    private Customer customer;
    
    /** The payment no. */
    private String paymentNo;
    
    /** The payment date. */
    private Date paymentDate;
    
    /** The payment amt. */
    private Long paymentAmt;
    
    /** The description. */
    private String description;

    /**
     * The Constructor.
     */
    public Payment() {
    }

    /**
     * Gets the payment id.
     *
     * @return the payment id
     */
    public int getPaymentId() {
	return paymentId;
    }

    /**
     * Sets the payment id.
     *
     * @param paymentId the payment id
     */
    public void setPaymentId(int paymentId) {
	this.paymentId = paymentId;
    }

    /**
     * Gets the sales person.
     *
     * @return the sales person
     */
    public SalesPerson getSalesPerson() {
	return salesPerson;
    }

    /**
     * Sets the sales person.
     *
     * @param salesPerson the sales person
     */
    public void setSalesPerson(SalesPerson salesPerson) {
	this.salesPerson = salesPerson;
    }

    /**
     * Gets the customer.
     *
     * @return the customer
     */
    public Customer getCustomer() {
	return customer;
    }

    /**
     * Sets the customer.
     *
     * @param customer the customer
     */
    public void setCustomer(Customer customer) {
	this.customer = customer;
    }

    /**
     * Gets the payment no.
     *
     * @return the payment no
     */
    public String getPaymentNo() {
	return paymentNo;
    }

    /**
     * Sets the payment no.
     *
     * @param paymentNo the payment no
     */
    public void setPaymentNo(String paymentNo) {
	this.paymentNo = paymentNo;
    }

    /**
     * Gets the payment date.
     *
     * @return the payment date
     */
    public Date getPaymentDate() {
	return paymentDate;
    }

    /**
     * Sets the payment date.
     *
     * @param paymentDate the payment date
     */
    public void setPaymentDate(Date paymentDate) {
	this.paymentDate = paymentDate;
    }

    /**
     * Gets the payment amt.
     *
     * @return the payment amt
     */
    public Long getPaymentAmt() {
	return paymentAmt;
    }

    /**
     * Sets the payment amt.
     *
     * @param paymentAmt the payment amt
     */
    public void setPaymentAmt(Long paymentAmt) {
	this.paymentAmt = paymentAmt;
    }

    /**
     * Gets the description.
     *
     * @return the description
     */
    public String getDescription() {
	return description;
    }

    /**
     * Sets the description.
     *
     * @param description the description
     */
    public void setDescription(String description) {
	this.description = description;
    }

}
