/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2015-04-14 06:17:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.themes.default_.modules;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vn.edu.cit.services.UserService;
import vn.edu.cit.model.*;
import org.springframework.data.mongodb.core.*;

public final class services_002dcontent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1421222476495L));
    _jspx_dependants.put("jar:file:/D:/Github/lv-nhan/contats/Codes/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ServerControl/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ajaxStart(function() {\r\n");
      out.write("\t\t$(\".wait\").css(\"display\", \"block\");\r\n");
      out.write("\t});\r\n");
      out.write("\t//loading ServerInfomation\r\n");
      out.write("\tvar ip = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server.serverAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t$(document)\r\n");
      out.write("\t\t\t.ready(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getserverinfo/'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ ip + '/' + cc,\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype : 'GET',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata : {},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//timeout : 60000,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess : function(data, status) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//if(data != null){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar html = '<table class=\"table table-bordered\">';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml += '<tr><td>Hostname:</td><td>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ data.hostname + '</td></tr>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml += '<tr><td>OS Version:</td><td>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ data.osversion + '</td></tr>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml += '<tr><td>Kernel:</td><td>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ data.kernel + '</td></tr>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml += '<tr><td>Processor Info:</td><td>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ data.processor_info\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ '</td></tr>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml += '<tr><td>Uptime:</td><td>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ data.uptime + '</td></tr>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml += '<tr><td>Memory:</td><td>Used: '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ parseInt(parseInt(data.memused) / 1024)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ ' MB - Total: '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ parseInt(parseInt(data.memtotal) / 1024)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ ' MB</td></tr>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml += '<tr><td>Cpu Loadaverage:</td><td>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ data.cpu_loadaverage\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ '</td></tr></table>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//\talert(html);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\".serverinfomation\").html(html);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\".wait\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#m-status\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.on(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"click\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//var id=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif ($(this).is(\":checked\")) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/monitor/start/'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ip\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '/'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ cc,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype : 'GET',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdatastatus : {}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/monitor/stop/'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ip\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '/'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ cc,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype : 'GET',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdatastatus : {}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\".active-sudo\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.on(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"click\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar user = $(\".username\").val();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar pass = $(\".password\").val();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/serviceconfig/user/'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ user\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '/'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ pass\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '/'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ip + '/' + cc,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype : 'GET',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdatastatus : {},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess : function(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdatastatus,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstatus) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("<aside class=\"right-side\">\r\n");
      out.write("\t<!-- Content Header (Page header) -->\r\n");
      out.write("\t<section class=\"content-header\">\r\n");
      out.write("\t\t<h1>\r\n");
      out.write("\t\t\tControl Services Server<small> (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server.serverAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</small>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!--  End Content Header -->\r\n");
      out.write("\t<!--  Main Content -->\r\n");
      out.write("\t<section class=\"content\">\r\n");
      out.write("\t\t<div class=\"main-content panel-group\" id=\"accordion\">\r\n");
      out.write("\t\t\t<ul class=\"nav nav-tabs\" id=\"serverTab\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a data-toggle=\"tab\" href=\"#monitor\">System\r\n");
      out.write("\t\t\t\t\t\tInfomation</a></li>\r\n");
      out.write("\t\t\t\t<li><a data-toggle=\"tab\" href=\"#services\">Service Configuation</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t<div style=\"display: none ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${display}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"login-alert\" class=\"alert alert-danger col-sm-12\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t<div style=\"display: none ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${displaysuccess}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"login-alert\" class=\"alert alert-success col-sm-12\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Tabs Monitor Config -->\r\n");
      out.write("\t\t\t\t<div class=\"tab-pane active\" id=\"monitor\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"panel-title\">System Infomation</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"serverinfomation\" class=\"serverinfomation\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"wait\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"display: none: text-align:center; displar: block; margin: 100px auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- // Panel Body -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\tMonitoring\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"m-status\" type=\"checkbox\" name=\"status\" class=\"m-checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#monitoring\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"\" for=\"m-status\"> On/Off Monitor Service </label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"monitoring\" class=\"monitoring panel-collapse collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/monitor/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server.serverAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Go\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tto Monitoring</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- // Panel Body -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Tabs Service Config -->\r\n");
      out.write("\t\t\t\t<div class=\"tab-pane\" id=\"services\">\r\n");
      out.write("\t\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/themes/default/modules/services-content.jsp(172,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest((session.getAttribute("sudouser") == null));
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
          out.write("\t\t\t\t\t\t\t<div style=\"padding-top: 30px\" class=\"panel-body\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<form action=\"#\" class=\"form-horizontal\" method=\"POST\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\"><label>Please input your server SUDOER user, it will not save!</label></div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group \">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-9\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control username\" name=\"username\" type=\"text\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Sudoer Username\" />\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group \">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-9\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control password\" name=\"password\" type=\"password\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Sudoer Password\" />\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary active-sudo\">OK</button>\r\n");
          out.write("\t\t\t\t\t\t\t\t</form>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/themes/default/modules/services-content.jsp(194,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest((session.getAttribute("sudouser") != null));
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<!-- Network Card -->\r\n");
          out.write("\t\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" data-toggle=\"collapse\" data-target=\"#network-card-config\">Network\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tConfiguration <i class=\"glyphicon glyphicon-chevron-down pull-right\"></i>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</h3>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t<div id=\"network-card-config\" class=\"panel-collapse collapse\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a class=\"col-md-4\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/serviceconfig/nic/interfaces/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server.serverAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tNetwork Interfaces </a> <a class=\"col-md-4\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/serviceconfig/nic/nameservers/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server.serverAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tDNS NameServers... </a> <a class=\"col-md-4\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/serviceconfig/nic/edit-file-nic/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server.serverAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tEdit Config File... </a>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<!-- FTP Service -->\r\n");
          out.write("\t\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/serviceconfig/ftp/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server.serverAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">FTP\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tServer Configuration <i\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right pull-right\"></i>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</h3>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t<!-- SSH Service -->\r\n");
          out.write("\t\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/serviceconfig/ssh/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server.serverAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">SSH\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tServer Configuration <i\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right pull-right\"></i>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</h3>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<!-- Apache Service -->\r\n");
          out.write("\t\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/serviceconfig/apache/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server.serverAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">Apache\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tServer Configuration <i\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-down pull-right\"></i>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</h3>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<!-- DHCP Service -->\r\n");
          out.write("\t\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/serviceconfig/dhcp/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server.serverAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">DHCP\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tServer Configuration <i\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-down pull-right\"></i>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</h3>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<!-- DNS Bind 9 -->\r\n");
          out.write("\t\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/serviceconfig/bind9/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server.serverAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">DNS\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tBind9 Server Configuration <i\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-down pull-right\"></i>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</h3>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- End Service -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!--  End Main Content -->\r\n");
      out.write("</aside>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/themes/default/modules/services-content.jsp(134,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/resources/themes/default/images/loading.gif");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }
}
